### PR TITLE
Add run_constrained crc32c

### PR DESCRIPTION
**Pull request by mbargull**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

This package conflicts with https://github.com/conda-forge/crc32c-feedstock/blob/2fea684eac53875b03cb4d32a97dbf181c6b075d/recipe/meta.yaml#L26-L28.
Adding a `run_constrained` with an unsatisfiable version `<0a0` prevents both packages to be installed alongside each other.
cc @johanneskoester

### CODE REVIEW

**Review by tswast — APPROVED** [review]
Thanks

**Comment by mbargull** [comment]
@tswast, thanks for merging!
Since this package has only been up recently, would you be okay with marking all previous builds as broken?
If we don't do that, `conda` could still pick up those older builds in some situation.
If we move them to the `broken` label, then we can make sure that existing users of the `crc32c` package won't be able to break their environments if older `goolge-crc32c` builds would have been pulled in.

**Comment by tswast** [comment]
Yes, marking the previous builds as broken seems reasonable. There aren't many of them.

**Comment by mbargull** [comment]
Great, thanks, I'll prepare a PR for https://github.com/conda-forge/admin-requests/ and will ping you in.

**Pull request merged**
